mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("planner.urls")),
    path("accounts/", include("allauth.urls"))
]

planner/urls.py
from django.urls import path
from . import views

app_name = "planner"

urlpatterns = [
    path("", views.IndexView.as_view(), name = "IndexView"),
    path("recipes/", views.RecipeList.as_view(), name = "recipe_list"),
    path("create/", views.CreateRecipe.as_view(), name = "recipe_create"),
    path("update/<int:pk>", views.UpdateRecipe.as_view(), name = "recipe_update"),
    path("delete/<int:pk>", views.DeleteRecipe.as_view(), name = "recipe_delete"),
    path("recipes/pdf", views.RecipeListPDF.as_view(), name = "recipe_list_pdf"),
    path("user/update/<int:pk>", views.UserProfile.as_view(), name = "user_update")
]

planner/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Recipe(models.Model):
    class Weekday(models.IntegerChoices):
        Monday = 1
        Tuesday = 2
        Wednesday = 3
        Thursday = 4
        Friday = 5
        Saturday = 6
        Sunday = 7
    day_of_the_week = models.IntegerField(choices=Weekday.choices)

    def get_weekday_label(self):
        return self.Weekday(self.day_of_the_week).label

    class MealType(models.IntegerChoices):
        Breakfast = 1
        Lunch = 2
        Dinner = 3
    meal_type = models.IntegerField(choices=MealType.choices)

    def get_meal_type_label(self):
        return self.MealType(self.meal_type).label

    recipe_name = models.CharField(max_length=100)
    recipe_description = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user}-{self.get_weekday_label()}-{self.get_meal_type_label()}"

planner/forms.py
from django.forms import ModelForm

from planner.models import Recipe

class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ["day_of_the_week", "meal_type", "recipe_name", "recipe_description"]

planner/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from planner.models import Recipe
from django.urls import reverse_lazy
from planner.forms import RecipeForm
from django.contrib import messages
from django.contrib.auth.models import User

# Create your views here.
class IndexView(TemplateView):
    template_name = "planner/index.html"

class RecipeList(ListView):
    template_name = "planner/recipe_list.html"
    model = Recipe
    # queryset = Recipe.objects.all()
    context_object_name = "recipe_list"
    http_method_names = ["get"]

    def get_queryset(self):
        queryset = self.model.objects.filter(user=self.request.user).order_by("day_of_the_week", "meal_type")
        return queryset

class CreateRecipe(CreateView):
    template_name = "planner/recipe_form.html"
    model = Recipe
    success_url = reverse_lazy("planner:recipe_list")
    context_object_name = "form"
    http_method_names = ["get", "post"]
    fields = ["day_of_the_week", "meal_type", "recipe_name", "recipe_description"]

    def post(self, request):
        form = RecipeForm(request.POST)
        if not form.is_valid():
            context = {"form":form}
            return render(request, self.template_name, context)
        
        obj = form.save(commit = False)
        obj.user = self.request.user
        obj.save()

        messages.success(request, "Your recipe has been created successfully. ")
        return redirect(self.success_url)
    
class UpdateRecipe(UpdateView):
    template_name = "planner/recipe_form.html"
    model = Recipe
    success_url = reverse_lazy("planner:recipe_list")
    context_object_name = "form"
    http_method_names = ["get","post"]
    fields = ["day_of_the_week", "meal_type", "recipe_name", "recipe_description"]
    # form_class = RecipeForm

    def post(self, request, *args, **kwargs):
        recipe = get_object_or_404(self.model, id=self.kwargs["pk"])
        if recipe.user == self.request.user:
            form = RecipeForm(request.POST, instance=recipe)
            if not form.is_valid():
                context = {"form":form}
                return render(request, self.template_name, context)
            
            form.save()
            messages.success(request, "Your recipe has been updated successfully.")
        else:
            messages.error(request, "Your recipe has been not updated successfully.")
        
        return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super(UpdateRecipe, self).get_context_data(**kwargs)
        context["form_type"] = "Update"
        return context

class DeleteRecipe(DeleteView):
    template_name = "planner/recipe_confirm_delete.html"
    model = Recipe
    context_object_name = "recipe"
    pk_url_kwarg = "pk"
    success_url = reverse_lazy("planner:recipe_list")
    http_method_names = ["get", "post"]

class RecipeListPDF(ListView):
    template_name = "planner/recipe_list_pdf.html"
    model = Recipe
    context_object_name = "recipe_list"
    http_method_names = ['get']

    def get_queryset(self):
        queryset = self.model.objects.filter(user=self.request.user).order_by("day_of_the_week", "meal_type")
        return queryset
    
class UserProfile(UpdateView):
    template_name = "planner/user_form.html"
    model = User
    success_url = reverse_lazy("planner:recipe_list")
    context_object_name = "form"
    http_method_names = ["get","post"]
    fields = ["first_name", "last_name"]

    

planner/templates/planner/index.html
{% extends "base_master.html" %}
{% block title %}
    Recipe Meal Planner
{% endblock title %}
{% load static %}
{% block content %}
<div class="container my-5">
    <div class="p-5 text-center bg-body-tertiary rounded-3">
      <img src="{% static 'planner/img/meal.png' %}" alt="RMP" width="200">
      <h1 class="text-body-emphasis">Recipe Meal Planner</h1>
      <p class="col-lg-8 mx-auto fs-5 text-muted">
        If you love meal planning and staying organized, Plan to Eat was created for you!
      </p>
      {% if not request.user.is_authenticated %}
        <div class="d-inline-flex gap-2 mb-5">
          <button class="d-inline-flex align-items-center btn btn-primary btn-lg px-4 rounded-pill" type="button" onclick="window.location='{% url 'account_signup' %}'">
            Get Started
          </button>
        </div>
      {% endif %}
      
    </div>
</div>
{% endblock content %}

planner/templates/planner/recipe_confirm_delete.html
{% extends "base_master.html" %}
{% block title %}
    Recipe Confirm Delete
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <h1>Delete Recipe</h1>
        <h3 class="mt-3">Are you sure you want to delete recipe <span class="text-danger">{{recipe.recipe_name}}</span>?</h3>
        <form action="" method="post">
            {% csrf_token %}
            <input class="btn btn-danger mt-3" type="submit" value="Yes">
            <button class="btn btn-warning mt-3" type="button"
            onclick="window.location = '{% url 'planner:recipe_list' %}'">No</button>
        </form>
    </div>
{% endblock content %}

planner/templates/planner/recipe_form.html
{% extends "base_master.html" %}
{% load bootstrap5 %}
{% block title %}
    Recipe Form
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        {% if form_type == "Update" %}
            <h1>Update a New Recipe</h1>
        {% else %}
            <h1>Create a New Recipe</h1>
        {% endif %}
        <hr>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary">
                {% if form_type == "Update" %}
                    Update Recipe
                {% else %}
                    Create Recipe
                {% endif %}
            </button>
            <button type="button" class="btn btn-danger"
            onclick="window.location = '{% url 'planner:recipe_list' %}'">Back</button>
        </form>
    </div>
{% endblock content %}

planner/templates/planner/recipe_list.html
{% extends "base_master.html" %}
{% block title %}
    Recipe List
{% endblock title %}
{% load static %}
{% block content %}
    <div class="container mt-3">
        <h1>Recipes</h1> 
        <button class="btn btn-primary mt-2 mb-2" onclick="window.location = '{% url 'planner:recipe_create' %}'">Create Recipe</button>
        {% if recipe_list %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Day</th>
                        <th scope="col">Time</th>
                        <th scope="col">Recipe Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                {% for recipe in recipe_list %}
                    <tr>
                        <td>{{recipe.get_weekday_label}}</td>
                        <td>{{recipe.get_meal_type_label}}</td>
                        <td>{{recipe.recipe_name}}</td>
                        <td>{{recipe.recipe_description}}</td>
                        <td>
                            <button class="btn btn-primary" onclick="window.location = '{% url 'planner:recipe_update' recipe.id %}'">Edit</button>
                            <button class="btn btn-danger" onclick="window.location = '{% url 'planner:recipe_delete' recipe.id %}'">Delete</button>
                        </td>
                    </tr>                    
                {% endfor %}
            </table>
        {% else %}
            <div class="alert alert-info mt-3">
                <p>There are no recipes in database.</p>
            </div>
        {% endif %}
        <button type="button" class="btn btn-info" onclick="window.location = '{% url 'planner:recipe_list_pdf' %}'">Generate PDF</button>
    </div>
{% endblock content %}

planner/templates/planner/recipe_list_pdf.html
{% extends "base_master.html" %}
{% block title %}
    Recipe List PDF
{% endblock title %}
{% block content %}
    <div class="container mt-3">
        <h1>Hello 
                    {{request.user.first_name}}
                  
                    {{request.user.last_name}} 
        </h1>
        <button type="button" class="btn btn-primary" onclick="generatePDF('{{request.user}}')">Download PDF</button>
        <hr>
        {% if user.is_authenticated %}
            <div class="recipe-container">
                <h1>Recipe Meal Planner</h1>
                <table class="table table-bordered border-dark">
                    <thead class="table-info border-dark">
                        <tr>
                            <th>Day</th>
                            <th>Time</th>
                            <th>Name</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    {% for recipe in recipe_list %}
                        <tr>
                            <td>{{recipe.get_weekday_label}}</td>
                            <td>{{recipe.get_meal_type_label}}</td>
                            <td>{{recipe.recipe_name}}</td>
                            <td>{{recipe.recipe_description}}</td>
                        </tr>
                    {% endfor %}
                </table>
                <p>Meal Plan designed by <span class="text-primary fw-bold">{{request.user}}</span>.</p>
            </div>
            <button class="btn btn-secondary" onclick="window.location = '{% url 'planner:recipe_list' %}'">Back</button>
        </div>
        {% endif %}
        
        
    <!-- html2pdf -->
    <!-- Reference: https://ekoopmans.github.io/html2pdf.js/ -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <script>
        function generatePDF(username)
        {
            var element = document.querySelector('.recipe-container');
            var opt = {
                margin: 1,
                // filename: username + "_recipe_meal_planner.pdf",
                filename: username.concat("_meal_planner.pdf"),
                jsPDF: {unit: 'in', format: 'a4', orientation: 'landscape'}
            };
            html2pdf().set(opt).from(element).save();
        }
    </script>
{% endblock content %}

planner/templates/planner/user_form.html
{% extends "base_master.html" %}
{% load bootstrap5 %}
{% block title %}
    Update Profile
{% endblock title %}
{% block content %}
    <div class="container">
        <h1>Update Profile</h1>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary">Update</button>
            <button class="btn btn-danger">Cancel</button>
        </form>
    </div>
{% endblock content %}

templates/base_master.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
                Recipe Meal Planner
            {% endblock title %}
        </title>
        {% bootstrap_css %}
    </head>
    <body>
        {% include "includes/navbar.html" %}
        
        {% block content %}

        {% endblock content %}
    </body>
    {% bootstrap_javascript %}
</html>

templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Recipe Meal Planner Navbar">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img src="{% static 'planner/img/meal.png' %}" alt="RMP" width="30"> 
          Recipe Meal Planner
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" 
        aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav me-auto mb-2 mb-sm-0">
              {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'planner:recipe_list' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'planner:user_update' request.user.id %}">Profile</a>
                </li>
              {% endif %}
            </ul>
            <ul class="navbar-nav mb-2 mb-sm-0">
                <li class="nav-item dropdown">
                  {% if user.is_authenticated %}
                    <a class="btn btn-danger m-1" href="{% url 'account_logout' %}">Logout</a>
                  {% else %}
                    <a class="btn btn-outline-light m-1" href="{% url 'account_login' %}">Login</a>
                  {% endif %}
                </li>
            </ul>      
        </div>
    </div>
</nav>